lib: Fix build with libc++
src/parser.hh:1407:29: error: no member named 'max' in namespace 'std'
src/boxed.hh:39:30: error: no type named 'in_place_t' in namespace 'std'

Fixes: https://gitlab.gnome.org/GNOME/vte/-/merge_requests/8
(cherry picked from commit 51cbd040814f8b08c05369c12ec73200923da4fe)